# Generated by Django 4.2.2 on 2023-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='type_event',
        ),
    ]
