# Generated by Django 4.2.2 on 2023-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
