# Generated by Django 4.2.2 on 2023-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
