# Generated by Django 4.2.2 on 2023-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(to='main_app.vendor'),
        ),
    ]
