# Generated by Django 4.2.2 on 2023-06-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_event_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='main_app.vendor'),
        ),
    ]
