# Generated by Django 4.2.2 on 2023-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_event_photo_alter_event_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
    ]
